dist: xenial
language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"

services:
  - xvfb

before_install:
  - "export DISPLAY=:99.0"
  - sudo apt-get install gfortran libblas-dev liblapack-dev mpich libmpich-dev

install:
  - pip install scipy mpi4py nose codecov scikit-learn==0.21rc2
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=cbayes --cover-erase --cover-html
  - mpirun -n 2 nosetests
  - pip uninstall -y mpi4py
  - nosetests

# notification settings
notifications:
    email:
        recipients:
            - consistentbayes@gmail.com
        on_success: change
        on_failure: always

# whitelist
branches:
    only:
        - master

# Push the results back to codecov
after_success:
  - codecov
